name = "fitness-tracker"
compatibility_date = "2024-12-29"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "jefit-db"
database_id = "61cc77ae-0b71-4689-b55e-5e0a6a33cfda"
